### ISSUE TITLE
Dynamically generate docker-compose.yml

### ISSUE THREAD

**Issue by bitwiseguy** [ethereum-oasis/baseline#160]
## Overview

In order to make the baseline environment flexible, we need the ability to modify baseline containers based on configuration choices. These choices should be made at a high level and in a single file, rather than having to modify multiple files or parse through hundreds of lines of code. By dynamically creating a docker-compose file, we can alter docker containers based on a user's simple preferred configuration.

### Implementation

Within the `radish34/` directory there is a `env.dev.env` file. Those environment variables are read by the `radish34/ops/dockerCompose_dev.sh` script, which then creates the `radish34/config/docker-compose.tmp.yml` file based on the env var values. The temporary `docker-compose.tmp.yml` file acts as an override to the default `radish34/docker-compose.yml` container definitions.

This work is part of the [init-core](https://github.com/ethereum-oasis/baseline/tree/init-core) branch.

### Acceptance

We should be able to configure the following by setting environment variables in a single .env file:
- Messenger provider: whisper vs. nats
- Log level/verbosity
- ZKP circuit selection: createMSA/createPO vs. dummy circuits vs. generic createAgreement
- Ethereum provider: ganache vs. Nethermind client (later add Besu)

## Tasks

- [x] Modify makefile to allow for both dev and prod environment setups
- [x] Allow the user to make all of their configuration choices by editing a single file
- [x] docker-compose file is generated based on user configuration choices
- [x] Move messenger config options into high level .env file
- [x] Docs reflect the new setup flow and provide instructions for configuration

**Comment by kthomas** [comment]
Nicely done @bitwiseguy
