### ISSUE TITLE
Create core baseline npm packages

### ISSUE THREAD

**Issue by bitwiseguy** [ethereum-oasis/baseline#161]
## Overview

In order to better differentiate the "core" baseline protocol code from the use-case specific code, we should create importable npm packages. This will make it easier on developers to apply the protocol to other use-cases.

### Questions

- Should the npm packages exist within this repo or be hosted on a public npm registry?
- Should we create a tag/release version for this initial cut of packages?

### Implementation

The following packages will be created:
- `@baseline-protocol/blockchain`
- `@baseline-protocol/messaging`
- `@baseline-protocol/persistence`
- `@baseline-protocol/privacy`

This core code will be pulled out of the radish34 code. It will exist inside the `<repo_root>/baseline/core` directory and get imported by the services that need the baseline protocol functionality.

This work is part of the [init-core](https://github.com/ethereum-oasis/baseline/tree/init-core) branch.

## Tasks

- [x] `make build` should recompile the npm packages
- [x] messenger service should import/use `@baseline/messaging` package
- [x] create test suites for each `@baseline` npm package

**Comment by conor10** [comment]
To the open questions - I would say yes to both. The more accessible the code is (i.e. available on NPM) the better.
Obviously it will need to be versioned too.

**Comment by kthomas** [comment]
Closing and deferring to the review of init-core.
