### ISSUE TITLE
Replace merkle-tree service with Nethermind Eth client RPCs

### ISSUE THREAD

**Issue by bitwiseguy** [ethereum-oasis/baseline#166]
## Overview

Currently, the Radish34 environment uses a shared `merkle-tree` service (aka `timber`), combined with `mongo-merkle-tree`, to listen for on-chain events emitted by the Shield/MerkleTree smart contracts and maintain an off-chain copy of the on-chain merkle tree. Nethermind is adding some `baseline_` RPC methods to their Ethereum client such that a separate `merkle-tree` service is not needed.

Once the Nethermind work is done, baseline should convert to using the client RPC in place of the dedicated `merkle-tree` service.

### Reference

Track Nethermind's baseline progress [here](https://github.com/NethermindEth/nethermind/projects/24#card-38073532)

### Questions

- Will Nethermind's client work with local test environment, which uses `ganache` for the blockchain layer?

### Tasks

- [x] Nethermind completes build of `baseline_` RPCs
- [x] Convert `merkle-tree` REST requests to Nethermind client RPCs
- [x] Add tests for new implementation
- [x] Update docs

**Comment by tkstanczak** [comment]
@bitwiseguy would you have time to give me an overview of the Ganache setups
I will also check with @matilote if he already tested it

**Comment by bitwiseguy** [comment]
@tkstanczak Sure, I am happy to discuss. I believe the setup is defined in the `command` section of the `ganache` docker container definition. I'm not sure if that gives you all the information you need though. We can discuss via Slack if you'd like.
```
  ganache:
    container_name: shared-ganache
    image: trufflesuite/ganache-cli:latest
    command: ganache-cli -m 'candy maple cake sugar pudding cream honey rich smooth crumble sweet treat' --db='/chaindata' --defaultBalanceEther 10000 --account="0xdad57e191799c38233bb7897f5ca66eb42d4f2f6d05ec657f8121b57e5d3bde6, 1000000000000000000000" --account="0x5aaa244692f54da4335a8553249b0db34316fbbc6ec353e1404cf77c415e59e8, 1000000000000000000000" --account="0x70441f8ed88f91416fbe21aa007357354e9bc30236211eda0022bdfb27beb227, 1000000000000000000000" --account="0x9ff4f711a85ed35d2cc66323abcd83f41e5981e0cd395800a262beb9a92b8abf, 1000000000000000000000" --account="0x77e701995d56e775bbb06559ece7d7352157106bbadc6aa5d8781c86c8d824bd, 1000000000000000000000" --networkId '333' --gasLimit 10000000
    ports:
      - 8545:8545
    networks:
      - network-buyer
      - network-supplier1
      - network-supplier2
    volumes:
      - chaindata:/chaindata
      - ./ops/ganache_health.sh:/app/health-check.sh:delegated
    healthcheck:
      test: ["CMD", "sh", "health-check.sh"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 10s
```

**Comment by kthomas** [comment]
This is in init-core 👍
