### ISSUE TITLE
Build baseline-protocol/privacy interface for a generic baseline zk circuit

### ISSUE THREAD

**Issue by bitwiseguy** [ethereum-oasis/baseline#168]
## Overview

Currently, Radish34 utilizes zkp circuits that are specifically designed to enforce business rules for supply chains (i.e. tiering structure of MSA). To help accelerate the adoption of the `baseline-protocol` by enabling any document to be "baselined" between multiple parties, we need a generic zkp circuit that is not tied to a specific use-case. The structure of the circuit is supposed on the following "core" components/statements to be proved/verified about the exchange of a generic document object between 2 parties:

a. The commitment of the document object is well formed, i.e., with the choice of the hashing scheme the commitment of the document can be proved to be the same as that computed outside the circuit
b. The commitment is co-signed by both the parties and the signature is verifiable
c. The root of the merkle tree calculated based on the commitment stored at a leaf index is consistent with the corresponding root on chain

### Assumptions
- Leveraging zokrates-js is currently feasible only as a wrapper around calls made as stdin's inside a container.
- Other tools under consideration for reference functionalities: circom, plonk

### Overall workflow considerations
General baseline document workflow requires the following steps:
  1. document created by sender
  1. document signed by sender
  1. document sent to recipient
  1. recipient inspects contents of document and signs if they agree
  1. recipient sends signed doc back to sender
  1. sender pushes commitment into Shield contract

## Tasks
- [x] `baselineDocument.zok` to model the business logic
- [x] Assess usage of Rust based calls for individual functionalities: compile, setup, computeWitness and generateProof
- [x] `@baseline-protocol/privacy` module built as a typescript interface (test with leveraging `zokrates-js`) with Rust
- [x] Alternate research around using golang interface for `@baseline-protocol/privacy` to bind rest calls made via golang to integrate with atomic functionalities

## Workflow Integration Tasks
Based on `simplify-msa-process` branch and `integration/simple-test.js`, as an example workflow
- [x] `createAgreement` zkp circuit exists in zkp service library
- [ ] `api` service supports graphQL `createAgreement` request
- [ ] Baseline config allows selection of `createAgreement` circuit via `env.dev.env` file
- [ ] Tests added to integration test suite for `createAgreement`
- [ ] Docs updated to explain purpose and usage of `createAgreement` circuit

**Comment by kthomas** [comment]
Given the title of this we can consider it to be completed as part of the init-core privacy work. Between the `core/privacy` package and the `examples/baseline-app` reference implementation, all of these considerations will have been accounted for when init-core review is completed and ships.
