### ISSUE TITLE
Create simplified baseline PoC

### ISSUE THREAD

**Issue by bitwiseguy** [ethereum-oasis/baseline#182]
## Overview

The radish34 PoC (proof of concept) and other instances in the `baseline/examples/` directory provide detailed, complex examples of how the baseline protocol can be used to add value to new and/or existing ERP software. The complexity of those examples makes it difficult for interested baseline users to learn about the protocol. In order to make it easier to learn about baseline, we should provide a simpler PoC that is more straightforward to follow.

## Questions

- How many "baselined" parties should be involved? Just two?
- Will the new PoC be configurable for the user to select options such as messenger provider type?
- What type of data will be "baselined" and what will its system of record (database type) be? 

## Tasks

- [ ] A new simple PoC should exist in the `baseline/examples` directory
- [ ] The new PoC should import and use the newly created `@baseline-protocol` npm packages
- [ ] Test suite should be provided to prove functionality
- [ ] Documentation should exist to explain the flow of the new PoC

**Comment by kthomas** [comment]
A new reference implementation lives under `examples/baseline-app`.

It shows Bob and Alice using the Baseline protocol. Some final work remains before it will be fully ready for review, so leaving this issue open for now.
