### ISSUE TITLE
Build capabilities to deploy and manage smart contracts on the mainnet

### ISSUE THREAD

**Issue by skarred14** [ethereum-oasis/baseline#19]
## Overview

As a developer/admin user, I would like to create a smart contract management suite to deploy, manage and update Baseline (as modeled in Radish34) smart contracts to the mainnet

### Reference

- [EIP1077](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1077.md)
- [Upgradable Contracts](https://docs.zeppelinos.org/docs/1.0.0/low_level_app)

### Questions

- What are the variations and consequences of Eth2.0? Should there be additional capabilities for handling web assembly adapters for smart contract languages?

### Acceptance

- Gas consumption metrics for upfront deployment and ongoing maintenace of Radish34 smart contracts on the mainnet
- Successfully run test cases for updated implementation based on upgradable and user managed smart contracts
- Successfully run test cases for updated implementation based on relaying capabilities using the EIP1077 standard

## Tasks

- [x] Build capabilities to deploy the existing Radish34 contracts on the mainnet
- [x] Update the deployment operation to be parameterized based on users registered in the `OrgRegistry` to create a managed user registration module under `deploy/`
- [ ] Build capabilities for the smart contracts to be upgradable using proxy patterns

**Disclaimer: This is a broad stroke and a sample feature request. It would need to be further updated (potentially broken down into further feature requests), based on discussions with other members of the Oasis community

**Comment by skarred14** [comment]
#88 #89

**Comment by skarred14** [comment]
#110

**Comment by kthomas** [comment]
See #256
