### ISSUE TITLE
Setup docker compatible health checks on all services 

### ISSUE THREAD

**Issue by breakpointer** [ethereum-oasis/baseline#51]
## Overview

As a developer using the Radish34 demo, such that I can reliably and repeatedly bring up the system, create a set of health checks for each service that test their readyness to be used. Tie these health checks into the docker compose file so service health can be reported. 

### Reference

- [Tutorial on health checks](https://blog.newrelic.com/engineering/docker-health-check-instruction/)
- [Docker health check docs](https://docs.docker.com/compose/compose-file/#healthcheck)

### Assumptions

- We will be able to setup dependencies in the docker-compose and health checks such that one liners like this `make && make start && make test` will reliably run. 
- This work will help with CI because we'll need to have a reliable and un-attended way to bring up the system to a testable state. 

### Acceptance

- Using `docker ps` view all the services that are up and their health status
- Setup docker compose to use the 'healthy' flag to gate the running of tests/system health

## Tasks

- [ ] Setup health checks on all services that look for process status AND key files needed for the demo
- [ ] Integrate health checks with docker compose
- [ ] Run repeated (at least 5 times in a row) system setup/teardown w/o failure
